language: java
jdk:
  - openjdk8
branches:
  only:
  - master

#travis home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

#메일 알림
notifications:
  email:
    recipients:
    - jtaeh57@gmail.com