language: java
jdk:
  - openjdk8
branches:
  only:
  - master

#travis home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

#메일 알림
notifications:
  email:
    recipients:
    - jtaeh57@gmail.com

#aws-deploy
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-exam-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: teahyuk/SpringExam
      branch: master