language: java
jdk:
  - openjdk8
branches:
  only:
  - master

#travis home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

#aws-deploy
before_deploy:
  - zip -r SpringExam *
  - mkdir -p deploy
  - mv SpringExam.zip deploy/SpringExam.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-exam-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: teahyuk/SpringExam
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: spring-exam-deploy # S3 버킷
    key: spring-exam-deploy.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springExam # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springExam-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: teahyuk/SpringExam
      branch: master

#메일 알림
notifications:
  email:
    recipients:
    - jtaeh57@gmail.com